---
- hosts: servers
  become: true
  tasks:
    - name: Replace listen 80 with listen {{ portnumber }} in NGINX default config
      copy:
        src: /etc/nginx/sites-enabled/default
        dest: /etc/nginx/sites-enabled/default

    - name: Copy the updated index.html from local to remote
      copy:
        src: /var/www/html/index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

