---
- name: Deploy NGINX container
  hosts: servers
  become: yes  # to run tasks as sudo

  tasks:
    - name: Ensure docker python library is installed
      pip:
        name: docker
        state: present

    - name: Deploy NGINX container on port 8000
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        published_ports:
          - "8000:80"
